AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200
  Exclude:
    - lib/humanize/locales/constants/*.rb

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/WordArray:
  Exclude:
    - lib/humanize/locales/constants/*.rb

Style/SpecialGlobalVars:
  Enabled: false
