LOTS = %w(hundred
          thousand
          million
          billion
          trillion
          quadrillion
          quintrillion
          sextillion
          septillion
          octillion
          nonillion
          decillion
          undecillion
          duodecillion
          tredecillion
          quattuordecillion
          quindecillion
          sexdecillion
          septendecillion
          octodecillion
          novemdecillion
          vigintillion
          unvigintillion
          duovigintillion
          tresvigintillion
          quattuortillion
          quintillion
          sestillion
          septemtillion
          octotillion
          novemtillion
          trigintillion
          untrigintillion
          duotrigintillion
          trestrayasillion
          quattuorcaturillion
          quinpancaillion
          sessatillion
          septemsaptaillion
          octoastaillion
          novemnavaillion
          tridasadecillion
          unishtenillion
          duositaillion
          tresshalashuillion
          quattuorerbettuillion
          unwillion
          duosnuillion
          treskhmtillion
          quattuorfawillion
          sessrswillion
          septemsfkhillion
          unyiillion
          duoerillion
          tressanillion
          quattuorsiillion
          quinwuillion
          duogoogol
          sesliuillion
          septemqiillion
          octobaillion
          novemjiuillion
          sessatillion
          tridecemillion
          unhenillion
          trestreisillion
          quattuortetoresillion
          quinpenteillion
          seshexaillion
          octodekaillion
          tresagoogol
          quinhoillion
          sesuacillion
          duoomeillion
          octochicanauiillion
          duoniillion
          tressanillion
          quattuorshiillion
          quingoillion
          sesrokuillion
          septemshichiillion
          octohachiillion
          novemkuillion
          duotwegenillion
          trespriillion
          quattuorfeowerillion
          octoeahtaillion
          novemnigonillion
          trityndecillion
          quattuorcethirillion
          quincoicillion
          sesseillion
          septemsechtillion
          octoochtillion
          novemnoinillion
          quattuorquattillion
          quincinqueillion
          sesseiillion
          septemsetteillion
          octoottoillion
          novemnoveillion
          tridiecidecillion
          quattuorcuatroillion
          sesseisillion
          tridiezdecillion
          unenillion
          duotoillion
          trestreeillion
          quattuorfireeillion
          quinfemoillion
          sesseksillion
          octoatteillion
          duoikiillion
          quattuordortillion
          septemyediillion
          octosekizillion
          sexagoogol
          triondecillion
          quinvjfillion
          septemzevenillion
          octoachtillion
          novemnegenillion
          tritiendecillion
          ununillion
          duodeuxillion
          trestroisillion
          quincinqillion
          sessixillion
          tridixdecillion
          unodinillion
          unalifillion
          duobaillion
          tresjimillion
          quattuordalillion
          quinhaillion
          seswaillion
          septemzayillion
          triyadecillion
          unotuillion
          quattuoranoillion
          quinisoillion
          sesissiiillion
          septemasaaillion
          novemtooluillion
          triiridecillion
          duounpaillion
          octagoogol
          octodopaupplaillion
          novemnupalaillion
          trishupaladecillion
          unettillion
          duotvaillion
          trestreillion
          quattuorfyraillion
          quinfemmillion
          sessexxillion
          ungesillion
          duominillion
          duodoiillion
          trestreiillion
          quattuorpatruillion
          quincinciillion
          sesnesillion
          septemsapteillion
          octooptillion
          duoeluaillion
          quattuorehaillion
          octoewalyillion
          unachatillion
          duoshtayimillion
          tresshaloshillion
          quattuorarbaiillion
          trieserdecillion
          unekillion
          duodoillion
          trestinillion
          quattuorcharillion
          quinpanchillion
          seschhaillion
          septemsatillion
          octoathillion
          novemnauillion
          trestgaiillion)